/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const BestTimeToCall = IDL.Variant({
  'morning' : IDL.Null,
  'evening' : IDL.Null,
  'anyTime' : IDL.Null,
  'afternoon' : IDL.Null,
});
export const CoverageType = IDL.Variant({
  'auto' : IDL.Null,
  'home' : IDL.Null,
  'life' : IDL.Null,
  'business' : IDL.Null,
});
export const QuoteSubmission = IDL.Record({
  'id' : IDL.Nat,
  'bestTimeToCall' : BestTimeToCall,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'zipCode' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'coverageType' : CoverageType,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuoteById' : IDL.Func([IDL.Nat], [QuoteSubmission], ['query']),
  'getQuoteSubmissions' : IDL.Func([], [IDL.Vec(QuoteSubmission)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, CoverageType, BestTimeToCall],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const BestTimeToCall = IDL.Variant({
    'morning' : IDL.Null,
    'evening' : IDL.Null,
    'anyTime' : IDL.Null,
    'afternoon' : IDL.Null,
  });
  const CoverageType = IDL.Variant({
    'auto' : IDL.Null,
    'home' : IDL.Null,
    'life' : IDL.Null,
    'business' : IDL.Null,
  });
  const QuoteSubmission = IDL.Record({
    'id' : IDL.Nat,
    'bestTimeToCall' : BestTimeToCall,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'zipCode' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'coverageType' : CoverageType,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuoteById' : IDL.Func([IDL.Nat], [QuoteSubmission], ['query']),
    'getQuoteSubmissions' : IDL.Func([], [IDL.Vec(QuoteSubmission)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, CoverageType, BestTimeToCall],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };