/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BestTimeToCall = { 'morning' : null } |
  { 'evening' : null } |
  { 'anyTime' : null } |
  { 'afternoon' : null };
export type CoverageType = { 'auto' : null } |
  { 'home' : null } |
  { 'life' : null } |
  { 'business' : null };
export interface QuoteSubmission {
  'id' : bigint,
  'bestTimeToCall' : BestTimeToCall,
  'name' : string,
  'email' : string,
  'zipCode' : string,
  'timestamp' : bigint,
  'phone' : string,
  'coverageType' : CoverageType,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQuoteById' : ActorMethod<[bigint], QuoteSubmission>,
  'getQuoteSubmissions' : ActorMethod<[], Array<QuoteSubmission>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuote' : ActorMethod<
    [string, string, string, string, CoverageType, BestTimeToCall],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];